# -*- coding: utf-8 -*-
"""Image Generation using Stable Diffusion

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pneaU5bMV9Nr1Fhz0tOQfH3aU0tSn_Ps
"""

# ============================================================
# EXPERIMENT 8
# IMAGE GENERATION USING DIFFUSION MODELS
# ============================================================

!pip install -q diffusers transformers accelerate torch

import torch
from diffusers import StableDiffusionPipeline

# Load Stable Diffusion model
pipe = StableDiffusionPipeline.from_pretrained(
    "runwayml/stable-diffusion-v1-5",
    torch_dtype=torch.float16
)

# Use GPU
pipe = pipe.to("cuda")

# Input prompt
prompt = "A futuristic city skyline at sunset, digital art, highly detailed"

# Generate image
image = pipe(
    prompt,
    num_inference_steps=30,
    guidance_scale=7.5
).images[0]

# Save image
image.save("generated_city.png")

# Display image
display(image)

print("Image generated and saved as generated_city.png")

# ============================================================
# EXPERIMENT 8
# IMAGE GENERATION USING STABLE DIFFUSION
# ============================================================

!pip install -q diffusers transformers accelerate torch

import torch
from diffusers import StableDiffusionPipeline

# ------------------------------------------------------------
# Check whether GPU is available
# ------------------------------------------------------------

if torch.cuda.is_available():
    device = "cuda"
    dtype = torch.float16
    print("GPU detected - using CUDA")
else:
    device = "cpu"
    dtype = torch.float32
    print("GPU not detected - using CPU")
    print("Image generation will take longer on CPU.")


# ------------------------------------------------------------
# Load Stable Diffusion model
# ------------------------------------------------------------

model_id = "runwayml/stable-diffusion-v1-5"

pipe = StableDiffusionPipeline.from_pretrained(
    model_id,
    torch_dtype=dtype
)

pipe = pipe.to(device)


# ------------------------------------------------------------
# Input prompt
# ------------------------------------------------------------

prompt = "A futuristic city skyline at sunset, digital art, highly detailed"


# ------------------------------------------------------------
# Generate image
# ------------------------------------------------------------

print("\nGenerating image...")

image = pipe(
    prompt,
    num_inference_steps=20,
    guidance_scale=7.5
).images[0]


# ------------------------------------------------------------
# Display image
# ------------------------------------------------------------

display(image)


# ------------------------------------------------------------
# Save image
# ------------------------------------------------------------

image.save("generated_city.png")

print("\nImage generated successfully!")
print("Saved as: generated_city.png")