# -*- coding: utf-8 -*-
"""Multimodal AI: Image Captioning + Visual Question Answering

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10dM1HJJmRUjksf7_YfqWLjfrlIsLm23e
"""

# ============================================================
# EXPERIMENT 9
# MULTIMODAL AI APPLICATION
# IMAGE CAPTIONING + VISUAL QUESTION ANSWERING
# ============================================================

!pip install -q transformers torch pillow requests

from transformers import (
    BlipProcessor,
    BlipForConditionalGeneration,
    BlipForQuestionAnswering
)
from PIL import Image
import requests

# ============================================================
# LOAD IMAGE
# ============================================================

image_url = "https://images.unsplash.com/photo-1519125323398-675f0ddb6308"

raw_image = Image.open(
    requests.get(image_url, stream=True).raw
).convert("RGB")

print("Image loaded successfully.")

display(raw_image)


# ============================================================
# 1. IMAGE CAPTIONING
# ============================================================

print("\nLoading Image Captioning model...")

cap_processor = BlipProcessor.from_pretrained(
    "Salesforce/blip-image-captioning-base"
)

cap_model = BlipForConditionalGeneration.from_pretrained(
    "Salesforce/blip-image-captioning-base"
)

# Prepare image
inputs = cap_processor(
    raw_image,
    return_tensors="pt"
)

# Generate caption
caption_ids = cap_model.generate(
    **inputs,
    max_new_tokens=30
)

# Decode caption
caption = cap_processor.decode(
    caption_ids[0],
    skip_special_tokens=True
)

print("\n==============================")
print("IMAGE CAPTIONING")
print("==============================")
print("Generated Caption:", caption)


# ============================================================
# 2. VISUAL QUESTION ANSWERING
# ============================================================

print("\nLoading VQA model...")

vqa_processor = BlipProcessor.from_pretrained(
    "Salesforce/blip-vqa-base"
)

vqa_model = BlipForQuestionAnswering.from_pretrained(
    "Salesforce/blip-vqa-base"
)

# Question
question = "What animal is in the picture?"

# Prepare image + question
vqa_inputs = vqa_processor(
    raw_image,
    question,
    return_tensors="pt"
)

# Generate answer
answer_ids = vqa_model.generate(
    **vqa_inputs
)

# Decode answer
answer = vqa_processor.decode(
    answer_ids[0],
    skip_special_tokens=True
)

print("\n==============================")
print("VISUAL QUESTION ANSWERING")
print("==============================")
print("Question:", question)
print("Answer:", answer)